#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import sys
import syslog
from netcop.actualizador import models
from netcop.actualizador.actualizador import Actualizador

despachante = False

try:
    from netcop.despachante import Despachante
    despachante = True
    syslog.syslog(syslog.LOG_DEBUG, "Se encontro despachante")
except ImportError:
    syslog.syslog(syslog.LOG_DEBUG, "Sin despachante")
    pass

try:
    syslog.openlog('actualizador')
    models.db.connect()
    actualizador = Actualizador()
    if actualizador.hay_actualizacion():
        actualizador.actualizar()
        if despachante:
            syslog.syslog(syslog.LOG_INFO, "Despachando politicas")
            Despachante().despachar()
    else:
        syslog.syslog(syslog.LOG_INFO, "No hay actualizaciones disponibles")
except Exception as inst:
    syslog.syslog(syslog.LOG_CRIT, "Error fatal: %s" % inst)
    sys.exit(1)
finally:
    syslog.closelog()
    if not models.db.is_closed():
        models.db.close()
