#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import sys
import syslog
import netcop
from netcop.actualizador import models

if __name__ == "__main__":
    syslog.openlog('actualizador')
    try:
        models.db.connect()
        actualizador = netcop.Actualizador()
        if actualizador.hay_actualizacion():
            actualizador.actualizar()
        else:
            syslog.syslog(syslog.LOG_INFO, 
                          "No hay actualizaciones disponibles")
    except:
        raise
        sys.exit(1)
    finally:
        syslog.closelog()
        if not models.db.is_closed():
            models.db.close()
